#!/usr/bin/env bash
# scripts/sync_marketing.sh
# Sync marketing/ files to marketing_public/ (Firebase Hosting source for LP)
# Source of truth: marketing/
#
# This script:
# 1. Generates product pages from products.json (+ nav/footer/sitemap)
# 2. Processes INCLUDE directives (header/footer injection)
# 3. Copies CSS, JS, assets, SEO files
# 4. Writes build info
#
# IMPORTANT: This script is independent from sync_public.sh.
# It never touches static/ or public/.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

cd "$PROJECT_ROOT"

# Guard: skip if marketing/ does not exist
if [[ ! -d "marketing" ]]; then
  echo "WARNING: marketing/ directory not found. Skipping marketing sync."
  exit 0
fi

echo "=========================================="
echo "Syncing marketing/ -> marketing_public/"
echo "=========================================="

BUILD_TIME=$(date +%Y%m%d%H%M%S)
echo "Build timestamp: $BUILD_TIME"

# ── Step 0: Clean and create output directory ──
rm -rf marketing_public
mkdir -p marketing_public/css marketing_public/js marketing_public/assets/images marketing_public/products

# ── Step 1: Generate product pages, nav links, sitemap ──
echo "Generating from marketing/config/products.json"
node ./scripts/generate_marketing.js

# ── Step 2: Copy and process pages with INCLUDE directives ──
PAGES=("index.html" "products.html" "privacy.html" "terms.html" "contact.html" "404.html")
copied=0

# Load template partials
HEAD_PARTIAL="$(cat marketing/templates/_head.html)"
HEADER_PARTIAL="$(cat marketing/templates/_header.html)"
FOOTER_PARTIAL="$(cat marketing/templates/_footer.html)"

process_includes() {
  local input_file="$1"
  local output_file="$2"

  # Use Python for reliable multi-line string replacement
  python3 -c "
import sys
content = open('$input_file', 'r').read()
head = open('marketing/templates/_head.html', 'r').read()
header = open('marketing/templates/_header.html', 'r').read()
footer = open('marketing/templates/_footer.html', 'r').read()
content = content.replace('<!-- INCLUDE:_head.html -->', head)
content = content.replace('<!-- INCLUDE:_header.html -->', header)
content = content.replace('<!-- INCLUDE:_footer.html -->', footer)
content = content.replace('__BUILD_TIME__', '$BUILD_TIME')
open('$output_file', 'w').write(content)
"
}

for page in "${PAGES[@]}"; do
  if [[ -f "marketing/pages/$page" ]]; then
    process_includes "marketing/pages/$page" "marketing_public/$page"
    echo "  Processed: marketing/pages/$page -> marketing_public/$page"
    ((copied++))
  fi
done

# ── Step 3: Process generated product pages ──
for product_page in marketing_public/products/*.html; do
  if [[ -f "$product_page" ]]; then
    tmp_file="${product_page}.tmp"
    process_includes "$product_page" "$tmp_file"
    mv "$tmp_file" "$product_page"
    echo "  Processed includes: $product_page"
    ((copied++))
  fi
done

# ── Step 4: Copy CSS, JS, assets ──
cp marketing/css/*.css marketing_public/css/
echo "  Copied: CSS files"

cp marketing/js/*.js marketing_public/js/
echo "  Copied: JS files"

# Copy all image assets
if ls marketing/assets/images/* 1>/dev/null 2>&1; then
  cp marketing/assets/images/* marketing_public/assets/images/
  echo "  Copied: image assets"
fi

# ── Step 5: Copy SEO files ──
cp marketing/seo/robots.txt marketing_public/robots.txt
echo "  Copied: robots.txt"
# sitemap.xml is generated by generate_marketing.js
echo "  Generated: sitemap.xml (by generate_marketing.js)"

# ── Step 6: Write build info ──
BUILD_SHA="${APP_VERSION:-${COMMIT_SHA:-$(git rev-parse --short HEAD 2>/dev/null || echo unknown)}}"
printf 'BUILD_SHA=%s\nBUILD_TIME_UTC=%s\n' "$BUILD_SHA" "$BUILD_TIME" > "marketing_public/build.txt"
echo "  Created: marketing_public/build.txt (SHA=$BUILD_SHA)"

echo "=========================================="
echo "Marketing sync complete: $copied page(s) processed"
echo "=========================================="

# --- Google Search Console verification (must be at site root) ---
if [ -f "marketing/seo/googlee7eac1f86c05ed22.html" ]; then
  cp -f "marketing/seo/googlee7eac1f86c05ed22.html" "marketing_public/"
fi